name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "GitHub Actions is working!"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t ecs-health-app:latest ./app